// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cart.sql

package db

import (
	"context"
	"database/sql"
)

const addToCart = `-- name: AddToCart :execresult
INSERT INTO cart (
  service_id, seller_id, category_id, quantity, price
) VALUES (
  ?, ?, ?, ?, ?
)
`

type AddToCartParams struct {
	ServiceID  int64 `json:"service_id"`
	SellerID   int64 `json:"seller_id"`
	CategoryID int64 `json:"category_id"`
	Quantity   int64 `json:"quantity"`
	Price      int64 `json:"price"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addToCart,
		arg.ServiceID,
		arg.SellerID,
		arg.CategoryID,
		arg.Quantity,
		arg.Price,
	)
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart WHERE id = ?
`

func (q *Queries) DeleteCartItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCartItem, id)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, service_id, seller_id, category_id, quantity, price, created_at, updated_at 
FROM cart
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCartItem(ctx context.Context, id int64) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartItem, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SellerID,
		&i.CategoryID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, service_id, seller_id, category_id, quantity, price, created_at, updated_at 
FROM cart
ORDER BY updated_at DESC
`

func (q *Queries) ListCartItems(ctx context.Context) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SellerID,
			&i.CategoryID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItem = `-- name: UpdateCartItem :execresult
UPDATE cart
SET quantity = ?, price = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCartItemParams struct {
	Quantity int64 `json:"quantity"`
	Price    int64 `json:"price"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCartItem, arg.Quantity, arg.Price, arg.ID)
}
