// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chat.sql

package db

import (
	"context"
	"database/sql"
)

const createChat = `-- name: CreateChat :execresult
INSERT INTO categories (
  name, description, created_by, updated_by
) VALUES (
  ?, ?, ?, ?
)
`

type CreateChatParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   int64          `json:"created_by"`
	UpdatedBy   int64          `json:"updated_by"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChat,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
}
