// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: items_order.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createItemOrder = `-- name: CreateItemOrder :execresult
INSERT INTO items_order (
  order_id, seller_id, quantity, price, status_service, start_date
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateItemOrderParams struct {
	OrderID       int64     `json:"order_id"`
	SellerID      int64     `json:"seller_id"`
	Quantity      int64     `json:"quantity"`
	Price         int64     `json:"price"`
	StatusService string    `json:"status_service"`
	StartDate     time.Time `json:"start_date"`
}

func (q *Queries) CreateItemOrder(ctx context.Context, arg CreateItemOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createItemOrder,
		arg.OrderID,
		arg.SellerID,
		arg.Quantity,
		arg.Price,
		arg.StatusService,
		arg.StartDate,
	)
}

const deleteItemOrder = `-- name: DeleteItemOrder :exec
DELETE FROM items_order
WHERE id = ?
`

func (q *Queries) DeleteItemOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemOrder, id)
	return err
}

const getItemOrderByID = `-- name: GetItemOrderByID :one
SELECT id, order_id, seller_id, quantity, price, status_service, start_date, created_at, updated_at
FROM items_order
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetItemOrderByID(ctx context.Context, id int64) (ItemsOrder, error) {
	row := q.db.QueryRowContext(ctx, getItemOrderByID, id)
	var i ItemsOrder
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.Quantity,
		&i.Price,
		&i.StatusService,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemOrders = `-- name: ListItemOrders :many
SELECT id, order_id, seller_id, quantity, price, status_service, start_date, created_at, updated_at
FROM items_order
ORDER BY created_at DESC
`

func (q *Queries) ListItemOrders(ctx context.Context) ([]ItemsOrder, error) {
	rows, err := q.db.QueryContext(ctx, listItemOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsOrder{}
	for rows.Next() {
		var i ItemsOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.Quantity,
			&i.Price,
			&i.StatusService,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemOrderStatus = `-- name: UpdateItemOrderStatus :execresult
UPDATE items_order
SET status_service = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateItemOrderStatusParams struct {
	StatusService string `json:"status_service"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateItemOrderStatus(ctx context.Context, arg UpdateItemOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItemOrderStatus, arg.StatusService, arg.ID)
}
