// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: negotiation.sql

package db

import (
	"context"
	"database/sql"
)

const createNegotiation = `-- name: CreateNegotiation :execresult
INSERT INTO negotiation (
  items_order_id, items_offer_id, status_negotiation, final_price
) VALUES (
  ?, ?, ?, ?
)
`

type CreateNegotiationParams struct {
	ItemsOrderID      int64  `json:"items_order_id"`
	ItemsOfferID      int64  `json:"items_offer_id"`
	StatusNegotiation string `json:"status_negotiation"`
	FinalPrice        int64  `json:"final_price"`
}

func (q *Queries) CreateNegotiation(ctx context.Context, arg CreateNegotiationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNegotiation,
		arg.ItemsOrderID,
		arg.ItemsOfferID,
		arg.StatusNegotiation,
		arg.FinalPrice,
	)
}

const deleteNegotiation = `-- name: DeleteNegotiation :exec
DELETE FROM negotiation
WHERE id = ?
`

func (q *Queries) DeleteNegotiation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNegotiation, id)
	return err
}

const getNegotiationByID = `-- name: GetNegotiationByID :one
SELECT id, items_order_id, items_offer_id, status_negotiation, final_price, created_at, updated_at
FROM negotiation
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetNegotiationByID(ctx context.Context, id int64) (Negotiation, error) {
	row := q.db.QueryRowContext(ctx, getNegotiationByID, id)
	var i Negotiation
	err := row.Scan(
		&i.ID,
		&i.ItemsOrderID,
		&i.ItemsOfferID,
		&i.StatusNegotiation,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNegotiationsByOfferID = `-- name: GetNegotiationsByOfferID :many
SELECT id, items_order_id, items_offer_id, status_negotiation, final_price, created_at, updated_at
FROM negotiation
WHERE items_offer_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetNegotiationsByOfferID(ctx context.Context, itemsOfferID int64) ([]Negotiation, error) {
	rows, err := q.db.QueryContext(ctx, getNegotiationsByOfferID, itemsOfferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Negotiation{}
	for rows.Next() {
		var i Negotiation
		if err := rows.Scan(
			&i.ID,
			&i.ItemsOrderID,
			&i.ItemsOfferID,
			&i.StatusNegotiation,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNegotiationsByOrderID = `-- name: GetNegotiationsByOrderID :many
SELECT id, items_order_id, items_offer_id, status_negotiation, final_price, created_at, updated_at
FROM negotiation
WHERE items_order_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetNegotiationsByOrderID(ctx context.Context, itemsOrderID int64) ([]Negotiation, error) {
	rows, err := q.db.QueryContext(ctx, getNegotiationsByOrderID, itemsOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Negotiation{}
	for rows.Next() {
		var i Negotiation
		if err := rows.Scan(
			&i.ID,
			&i.ItemsOrderID,
			&i.ItemsOfferID,
			&i.StatusNegotiation,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNegotiations = `-- name: ListNegotiations :many
SELECT id, items_order_id, items_offer_id, status_negotiation, final_price, created_at, updated_at
FROM negotiation
ORDER BY created_at DESC
`

func (q *Queries) ListNegotiations(ctx context.Context) ([]Negotiation, error) {
	rows, err := q.db.QueryContext(ctx, listNegotiations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Negotiation{}
	for rows.Next() {
		var i Negotiation
		if err := rows.Scan(
			&i.ID,
			&i.ItemsOrderID,
			&i.ItemsOfferID,
			&i.StatusNegotiation,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNegotiation = `-- name: UpdateNegotiation :execresult
UPDATE negotiation
SET status_negotiation = ?, final_price = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNegotiationParams struct {
	StatusNegotiation string `json:"status_negotiation"`
	FinalPrice        int64  `json:"final_price"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateNegotiation(ctx context.Context, arg UpdateNegotiationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNegotiation, arg.StatusNegotiation, arg.FinalPrice, arg.ID)
}
