// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (
  user_id,file_payment, method_payment, status_payment
) VALUES (
  ?, ?, ?, ?
)
`

type CreateOrderParams struct {
	UserID        int64  `json:"user_id"`
	FilePayment   string `json:"file_payment"`
	MethodPayment string `json:"method_payment"`
	StatusPayment string `json:"status_payment"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.UserID,
		arg.FilePayment,
		arg.MethodPayment,
		arg.StatusPayment,
	)
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = ?
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, file_payment, method_payment, status_payment, created_at, updated_at
FROM orders
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FilePayment,
		&i.MethodPayment,
		&i.StatusPayment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, file_payment, method_payment, status_payment, created_at, updated_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FilePayment,
			&i.MethodPayment,
			&i.StatusPayment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execresult
UPDATE orders
SET status_payment = ? , updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	StatusPayment string `json:"status_payment"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOrderStatus, arg.StatusPayment, arg.ID)
}
