// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (sql.Result, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error)
	CreateItemOrder(ctx context.Context, arg CreateItemOrderParams) (sql.Result, error)
	CreateNegotiation(ctx context.Context, arg CreateNegotiationParams) (sql.Result, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateQuotation(ctx context.Context, arg CreateQuotationParams) (sql.Result, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (sql.Result, error)
	CreateServicePhoto(ctx context.Context, arg CreateServicePhotoParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteCartItem(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteItemOrder(ctx context.Context, id int64) error
	DeleteNegotiation(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteQuotation(ctx context.Context, id int64) error
	DeleteService(ctx context.Context, id int64) error
	DeleteServicePhoto(ctx context.Context, serviceID int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCartItem(ctx context.Context, id int64) (Cart, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetItemOrderByID(ctx context.Context, id int64) (ItemsOrder, error)
	GetNegotiationByID(ctx context.Context, id int64) (Negotiation, error)
	GetNegotiationsByOfferID(ctx context.Context, itemsOfferID int64) ([]Negotiation, error)
	GetNegotiationsByOrderID(ctx context.Context, itemsOrderID int64) ([]Negotiation, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetQuotation(ctx context.Context, id int64) (Quotation, error)
	GetServiceByCategory(ctx context.Context, categoryID int64) ([]Service, error)
	GetServiceByID(ctx context.Context, id int64) (GetServiceByIDRow, error)
	GetServiceBySeller(ctx context.Context, sellerID int64) ([]GetServiceBySellerRow, error)
	GetServicePhotoByID(ctx context.Context, id int64) (ServicePhoto, error)
	GetServicePhotosByServiceID(ctx context.Context, serviceID int64) (ServicePhoto, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListCartItems(ctx context.Context) ([]Cart, error)
	ListCategory(ctx context.Context) ([]ListCategoryRow, error)
	ListItemOrders(ctx context.Context) ([]ItemsOrder, error)
	ListNegotiations(ctx context.Context) ([]Negotiation, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListQuotations(ctx context.Context) ([]Quotation, error)
	ListService(ctx context.Context) ([]ListServiceRow, error)
	ListServicePhotos(ctx context.Context) ([]ServicePhoto, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (sql.Result, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (sql.Result, error)
	UpdateItemOrderStatus(ctx context.Context, arg UpdateItemOrderStatusParams) (sql.Result, error)
	UpdateNegotiation(ctx context.Context, arg UpdateNegotiationParams) (sql.Result, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (sql.Result, error)
	UpdateQuotation(ctx context.Context, arg UpdateQuotationParams) (sql.Result, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (sql.Result, error)
	UpdateServicePhoto(ctx context.Context, arg UpdateServicePhotoParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
