// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: service.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createService = `-- name: CreateService :execresult
INSERT INTO services (
  seller_id, category_id, title, description, price, created_by, updated_by
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
`

type CreateServiceParams struct {
	SellerID    int64          `json:"seller_id"`
	CategoryID  int64          `json:"category_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	CreatedBy   int64          `json:"created_by"`
	UpdatedBy   int64          `json:"updated_by"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createService,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = ?
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getServiceByCategory = `-- name: GetServiceByCategory :many
SELECT id, seller_id, category_id, title, description, price, created_at, created_by, updated_at, updated_by 
FROM services
WHERE category_id = ?
`

func (q *Queries) GetServiceByCategory(ctx context.Context, categoryID int64) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServiceByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT s.id, seller_id, category_id, title, description, price, s.created_at, s.created_by, s.updated_at, s.updated_by, sp.id, service_id, photo_url, sp.created_at, sp.created_by, sp.updated_at, sp.updated_by 
FROM services s
INNER JOIN service_photos sp
ON s.id = sp.service_id
WHERE s.id = ?
LIMIT 1
`

type GetServiceByIDRow struct {
	ID          int64          `json:"id"`
	SellerID    int64          `json:"seller_id"`
	CategoryID  int64          `json:"category_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int64          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int64          `json:"updated_by"`
	ID_2        int64          `json:"id_2"`
	ServiceID   int64          `json:"service_id"`
	PhotoUrl    string         `json:"photo_url"`
	CreatedAt_2 time.Time      `json:"created_at_2"`
	CreatedBy_2 int64          `json:"created_by_2"`
	UpdatedAt_2 time.Time      `json:"updated_at_2"`
	UpdatedBy_2 int64          `json:"updated_by_2"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (GetServiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ID_2,
		&i.ServiceID,
		&i.PhotoUrl,
		&i.CreatedAt_2,
		&i.CreatedBy_2,
		&i.UpdatedAt_2,
		&i.UpdatedBy_2,
	)
	return i, err
}

const getServiceBySeller = `-- name: GetServiceBySeller :many
SELECT id, seller_id, category_id, title, description, price, created_at, created_by, updated_at, updated_by 
FROM services
WHERE seller_id = ?
`

func (q *Queries) GetServiceBySeller(ctx context.Context, sellerID int64) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, getServiceBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listService = `-- name: ListService :many
SELECT s.id, seller_id, category_id, title, description, price, s.created_at, s.created_by, s.updated_at, s.updated_by, sp.id, service_id, photo_url, sp.created_at, sp.created_by, sp.updated_at, sp.updated_by
FROM services s
INNER JOIN service_photos sp
ON s.id = sp.service_id
ORDER BY s.id
`

type ListServiceRow struct {
	ID          int64          `json:"id"`
	SellerID    int64          `json:"seller_id"`
	CategoryID  int64          `json:"category_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int64          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int64          `json:"updated_by"`
	ID_2        int64          `json:"id_2"`
	ServiceID   int64          `json:"service_id"`
	PhotoUrl    string         `json:"photo_url"`
	CreatedAt_2 time.Time      `json:"created_at_2"`
	CreatedBy_2 int64          `json:"created_by_2"`
	UpdatedAt_2 time.Time      `json:"updated_at_2"`
	UpdatedBy_2 int64          `json:"updated_by_2"`
}

func (q *Queries) ListService(ctx context.Context) ([]ListServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceRow{}
	for rows.Next() {
		var i ListServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ID_2,
			&i.ServiceID,
			&i.PhotoUrl,
			&i.CreatedAt_2,
			&i.CreatedBy_2,
			&i.UpdatedAt_2,
			&i.UpdatedBy_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :execresult
UPDATE services
SET seller_id = ?, category_id = ?, title = ?, description = ?, price = ?, updated_by = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateServiceParams struct {
	SellerID    int64          `json:"seller_id"`
	CategoryID  int64          `json:"category_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Price       int64          `json:"price"`
	UpdatedBy   int64          `json:"updated_by"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateService,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.UpdatedBy,
		arg.ID,
	)
}
